<?php

namespace EntrepriseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * gagnantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gagnantsRepository extends EntityRepository
{
}
