homepage:
    path:  /
    defaults: { _controller:FrontBundle:Default:index }
apropos:
    path:  /apropos
    defaults: { _controller:FrontBundle:Default:apropos }
contact:
    path:  /contact
    defaults: { _controller:FrontBundle:Default:contact }
boutique:
    path:  /boutique
    defaults: { _controller:FrontBundle:Default:boutique }
activity:
    path:  /activity/{id}
    defaults: { _controller:FrontBundle:Default:activityCat }
    requirements:
        id : \d+        
actsingle:
    path:  /actsingle/{id}
    defaults: { _controller:FrontBundle:Default:activity }
    requirements:
        id : \d+
monprofil:
    path:  /monprofil
    defaults: { _controller:FrontBundle:Default:monprofil }
add_activite:
    path:     /AddActivite
    defaults: { _controller:FrontBundle:Admin:AddActivite }
delete_activite:
    path:     /DeleteActivite
    defaults: { _controller:FrontBundle:Admin:DeleteActivite }
activation_activite:
    path:     /ActivationActivite
    defaults: { _controller:FrontBundle:Admin:ActivationActivite }
edit_activite:
    path:     /editActivite
    defaults: { _controller:FrontBundle:Admin:EditActivite }
add_produit:
    path:     /AddProduit
    defaults: { _controller:FrontBundle:Admin:AddProduit }
delete_produit:
    path:     /DeleteProduit
    defaults: { _controller:FrontBundle:Admin:DeleteProduit }
edit_stock_produit:
    path:     /EditStockProduit
    defaults: { _controller:FrontBundle:Admin:EditStockProduit }
edit_produit:
    path:     /editProduit
    defaults: { _controller:FrontBundle:Admin:EditProduit }
acheter_produit:
    path:     /acheterProduit
    defaults: { _controller:FrontBundle:Utilisateur:AcheterProduit }
