homepage:
    path:  /
    defaults: { _controller:FrontBundle:Default:index }
apropos:
    path:  /apropos
    defaults: { _controller:FrontBundle:Default:apropos }
contact:
    path:  /contact
    defaults: { _controller:FrontBundle:Default:contact }
boutique:
    path:  /boutique
    defaults: { _controller:FrontBundle:Default:boutique }
monprofil:
    path:  /monprofil/{config}
    defaults: { _controller:FrontBundle:Default:monprofil, config:"default" }
send_message_contact:
    path:  /SendMessageContact
    defaults: { _controller:FrontBundle:Default:SendMessageContact }
pharmacy_list:
    path:  /pharmacy_list/{type}
    defaults: { _controller:FrontBundle:Default:pharmacyList, type: null }
