entreprise_homepage:
    path:     /
    defaults: { _controller:EntrepriseBundle:Default:index }
gagnants:
    path:     /gagnants
    defaults: { _controller:EntrepriseBundle:Default:gagnants }
statistique:
    path:     /statistique
    defaults: { _controller:EntrepriseBundle:Default:statistique }
pub:
    path:     /pub
    defaults: { _controller:EntrepriseBundle:Default:pub }
enregistrerprofilEnt:
    path:  /enregistrerprofilEnt
    defaults: { _controller:EntrepriseBundle:Default:enregistrerprofil }
add_pub:
    path:     /AddPub
    defaults: { _controller:EntrepriseBundle:Default:AddPub }
delete_pub:
    path:     /DeletePub
    defaults: { _controller:EntrepriseBundle:Default:DeletePub }
duree_pub:
    path:     /DureePub
    defaults: { _controller:EntrepriseBundle:Default:DureePub }
edit_pub:
    path:     /EditPub
    defaults: { _controller:EntrepriseBundle:Default:EditPub }
save_entreprise_data:
    path:     /save_entreprise_data
    defaults: { _controller:EntrepriseBundle:Default:SaveEntrepriseData }
edit_imgcouverture_entreprise:
    path:     /editImgCouvertureEntreprise
    defaults: { _controller:EntrepriseBundle:Default:EditImgCouvertureEntreprise }
edit_imgprofil_entreprise:
    path:     /editImgProfilEntreprise
    defaults: { _controller:EntrepriseBundle:Default:EditImgProfilEntreprise }
