sup_admin_homepage:
    path:     /
    defaults: { _controller: SupAdminBundle:Default:index }
categories:
    path:     /categories
    defaults: { _controller: SupAdminBundle:Default:categories }
levels:
    path:     /levels
    defaults: { _controller: SupAdminBundle:Default:levels }
max_levels:
    path:     /Maxlevels
    defaults: { _controller: SupAdminBundle:Default:Maxlevels }
categories:
    path:     /categories
    defaults: { _controller: SupAdminBundle:Default:categories }
add_categorie:
    path:     /AddCategorie
    defaults: { _controller: SupAdminBundle:Default:AddCategorie }
delete_categorie:
    path:     /DeleteCategorie
    defaults: { _controller: SupAdminBundle:Default:DeleteCategorie }
activation_categorie:
    path:     /ActivationCategorie
    defaults: { _controller: SupAdminBundle:Default:ActivationCategorie }
edit_categorie:
    path:     /editCategorie
    defaults: { _controller: SupAdminBundle:Default:EditCategorie }
