admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
profils:
    path:     /profils
    defaults: { _controller: AdminBundle:Default:profils }
user_profil:
    path:     /UserProfil/{id}
    defaults: { _controller: AdminBundle:Default:userProfil }
    requirements:
        page: '\d+'
entreprise_profil:
    path:     /EntrepriseProfil/{id}
    defaults: { _controller: AdminBundle:Default:entrepriseProfil }
    requirements:
        page: '\d+'
admin_profil:
    path:     /AdminProfil/{id}
    defaults: { _controller: AdminBundle:Default:adminProfil }
    requirements:
        page: '\d+'
activation_profil:
    path:     /ActivationProfil
    defaults: { _controller: AdminBundle:Default:activationProfil }
edit_imgprofil_admin:
    path:     /editImgProfilAdmin
    defaults: { _controller:AdminBundle:Default:EditImgProfilAdmin }
edit_imgcouverture_admin:
    path:     /editImgCouvertureAdmin
    defaults: { _controller:AdminBundle:Default:EditImgCouvertureAdmin }
save_admin_data:
    path:     /save_admin_data
    defaults: { _controller:AdminBundle:Default:SaveAdminData }
