<?php

namespace SupAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cadeauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cadeauxRepository extends EntityRepository
{
}
