<?php

namespace SupAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * levelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class levelsRepository extends EntityRepository
{
}
