services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    authentication_handler:
        class:        UserBundle\Handler\AuthenticationHandler
        arguments:    [@router, @security.authorization_checker, @fos_user.user_manager, @service_container]